# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b02da646541fd779f953ab302236efc2654eb921c7ef4ca5a93e19aaf7b4a589540abf5f5a717b38f06793f9911264196c14c711a49d13bb071522f2d940aade

test:
  secret_key_base: 45fdd2c6c0ce16575a26c8156914a0e48d31030347a194fc27ed9ba6930a2ba27dbe67972a228e36546b571404ffe5750ab480fc31fcce31e1eaff0ad1b4e3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
